#include "main.h"

extern "C"
{
	EXPORT btContactSolverInfoData* btContactSolverInfoData_new();
	EXPORT btScalar btContactSolverInfoData_getDamping(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getErp(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getErp2(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getFriction(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getGlobalCfm(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getLinearSlop(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getMaxErrorReduction(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getMaxGyroscopicForce(btContactSolverInfoData* obj);
	EXPORT int btContactSolverInfoData_getMinimumSolverBatchSize(btContactSolverInfoData* obj);
	EXPORT int btContactSolverInfoData_getNumIterations(btContactSolverInfoData* obj);
	EXPORT int btContactSolverInfoData_getRestingContactRestitutionThreshold(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getRestitution(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getSingleAxisRollingFrictionThreshold(btContactSolverInfoData* obj);
	EXPORT int btContactSolverInfoData_getSolverMode(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getSor(btContactSolverInfoData* obj);
	EXPORT int btContactSolverInfoData_getSplitImpulse(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getSplitImpulsePenetrationThreshold(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getSplitImpulseTurnErp(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getTau(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getTimeStep(btContactSolverInfoData* obj);
	EXPORT btScalar btContactSolverInfoData_getWarmstartingFactor(btContactSolverInfoData* obj);
	EXPORT void btContactSolverInfoData_setDamping(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setErp(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setErp2(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setFriction(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setGlobalCfm(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setLinearSlop(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setMaxErrorReduction(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setMaxGyroscopicForce(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setMinimumSolverBatchSize(btContactSolverInfoData* obj, int value);
	EXPORT void btContactSolverInfoData_setNumIterations(btContactSolverInfoData* obj, int value);
	EXPORT void btContactSolverInfoData_setRestingContactRestitutionThreshold(btContactSolverInfoData* obj, int value);
	EXPORT void btContactSolverInfoData_setRestitution(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setSingleAxisRollingFrictionThreshold(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setSolverMode(btContactSolverInfoData* obj, int value);
	EXPORT void btContactSolverInfoData_setSor(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setSplitImpulse(btContactSolverInfoData* obj, int value);
	EXPORT void btContactSolverInfoData_setSplitImpulsePenetrationThreshold(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setSplitImpulseTurnErp(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setTau(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setTimeStep(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_setWarmstartingFactor(btContactSolverInfoData* obj, btScalar value);
	EXPORT void btContactSolverInfoData_delete(btContactSolverInfoData* obj);

	EXPORT btContactSolverInfo* btContactSolverInfo_new();

	EXPORT btContactSolverInfoDoubleData* btContactSolverInfoDoubleData_new();
	EXPORT double btContactSolverInfoDoubleData_getDamping(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getErp(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getErp2(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getFriction(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getGlobalCfm(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getLinearSlop(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getMaxErrorReduction(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getMaxGyroscopicForce(btContactSolverInfoDoubleData* obj);
	EXPORT int btContactSolverInfoDoubleData_getMinimumSolverBatchSize(btContactSolverInfoDoubleData* obj);
	EXPORT int btContactSolverInfoDoubleData_getNumIterations(btContactSolverInfoDoubleData* obj);
	EXPORT char* btContactSolverInfoDoubleData_getPadding(btContactSolverInfoDoubleData* obj);
	EXPORT int btContactSolverInfoDoubleData_getRestingContactRestitutionThreshold(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getRestitution(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getSingleAxisRollingFrictionThreshold(btContactSolverInfoDoubleData* obj);
	EXPORT int btContactSolverInfoDoubleData_getSolverMode(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getSor(btContactSolverInfoDoubleData* obj);
	EXPORT int btContactSolverInfoDoubleData_getSplitImpulse(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getSplitImpulsePenetrationThreshold(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getSplitImpulseTurnErp(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getTau(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getTimeStep(btContactSolverInfoDoubleData* obj);
	EXPORT double btContactSolverInfoDoubleData_getWarmstartingFactor(btContactSolverInfoDoubleData* obj);
	EXPORT void btContactSolverInfoDoubleData_setDamping(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setErp(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setErp2(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setFriction(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setGlobalCfm(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setLinearSlop(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setMaxErrorReduction(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setMaxGyroscopicForce(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setMinimumSolverBatchSize(btContactSolverInfoDoubleData* obj, int value);
	EXPORT void btContactSolverInfoDoubleData_setNumIterations(btContactSolverInfoDoubleData* obj, int value);
	EXPORT void btContactSolverInfoDoubleData_setPadding(btContactSolverInfoDoubleData* obj, char* value);
	EXPORT void btContactSolverInfoDoubleData_setRestingContactRestitutionThreshold(btContactSolverInfoDoubleData* obj, int value);
	EXPORT void btContactSolverInfoDoubleData_setRestitution(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setSingleAxisRollingFrictionThreshold(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setSolverMode(btContactSolverInfoDoubleData* obj, int value);
	EXPORT void btContactSolverInfoDoubleData_setSor(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setSplitImpulse(btContactSolverInfoDoubleData* obj, int value);
	EXPORT void btContactSolverInfoDoubleData_setSplitImpulsePenetrationThreshold(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setSplitImpulseTurnErp(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setTau(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setTimeStep(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_setWarmstartingFactor(btContactSolverInfoDoubleData* obj, double value);
	EXPORT void btContactSolverInfoDoubleData_delete(btContactSolverInfoDoubleData* obj);

	EXPORT btContactSolverInfoFloatData* btContactSolverInfoFloatData_new();
	EXPORT float btContactSolverInfoFloatData_getDamping(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getErp(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getErp2(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getFriction(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getGlobalCfm(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getLinearSlop(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getMaxErrorReduction(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getMaxGyroscopicForce(btContactSolverInfoFloatData* obj);
	EXPORT int btContactSolverInfoFloatData_getMinimumSolverBatchSize(btContactSolverInfoFloatData* obj);
	EXPORT int btContactSolverInfoFloatData_getNumIterations(btContactSolverInfoFloatData* obj);
	EXPORT char* btContactSolverInfoFloatData_getPadding(btContactSolverInfoFloatData* obj);
	EXPORT int btContactSolverInfoFloatData_getRestingContactRestitutionThreshold(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getRestitution(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getSingleAxisRollingFrictionThreshold(btContactSolverInfoFloatData* obj);
	EXPORT int btContactSolverInfoFloatData_getSolverMode(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getSor(btContactSolverInfoFloatData* obj);
	EXPORT int btContactSolverInfoFloatData_getSplitImpulse(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getSplitImpulsePenetrationThreshold(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getSplitImpulseTurnErp(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getTau(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getTimeStep(btContactSolverInfoFloatData* obj);
	EXPORT float btContactSolverInfoFloatData_getWarmstartingFactor(btContactSolverInfoFloatData* obj);
	EXPORT void btContactSolverInfoFloatData_setDamping(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setErp(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setErp2(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setFriction(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setGlobalCfm(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setLinearSlop(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setMaxErrorReduction(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setMaxGyroscopicForce(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setMinimumSolverBatchSize(btContactSolverInfoFloatData* obj, int value);
	EXPORT void btContactSolverInfoFloatData_setNumIterations(btContactSolverInfoFloatData* obj, int value);
	EXPORT void btContactSolverInfoFloatData_setPadding(btContactSolverInfoFloatData* obj, char* value);
	EXPORT void btContactSolverInfoFloatData_setRestingContactRestitutionThreshold(btContactSolverInfoFloatData* obj, int value);
	EXPORT void btContactSolverInfoFloatData_setRestitution(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setSingleAxisRollingFrictionThreshold(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setSolverMode(btContactSolverInfoFloatData* obj, int value);
	EXPORT void btContactSolverInfoFloatData_setSor(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setSplitImpulse(btContactSolverInfoFloatData* obj, int value);
	EXPORT void btContactSolverInfoFloatData_setSplitImpulsePenetrationThreshold(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setSplitImpulseTurnErp(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setTau(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setTimeStep(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_setWarmstartingFactor(btContactSolverInfoFloatData* obj, float value);
	EXPORT void btContactSolverInfoFloatData_delete(btContactSolverInfoFloatData* obj);
}
